apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: {{ .Values.argo.common.apps_namespace }}
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: 'apps-*'
      server: '*'
    - namespace: 'kube-system'
      server: '*'
  sourceRepos:
    - '*'
