{{- if .Values.deploy.use -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cider
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cider
      type: deploy
  template:
    metadata:
      labels:
        app: cider
        type: deploy
    spec:
      containers:
        - name: main
          image: docker.io/golang:alpine3.21
          command:
            - go
          args:
            - run
            - /app/main.go
          env:
            - name: HOME
              value: /goroot
            - name: VERSION
              value: "{{ .Values.version }}"
          readinessProbe:
            httpGet:
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 30000
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /app
              name: go-code
            - mountPath: /tmp
              name: tmp
            - mountPath: /goroot
              name: goroot
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: go-code
          configMap:
            name: golang-code
        - name: tmp
          emptyDir:
            sizeLimit: 1G
        - name: goroot
          emptyDir:
            sizeLimit: 1G
{{- end -}}
