{{- if .Values.deploy.use -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cider
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: cider
      type: deploy
  template:
    metadata:
      labels:
        app: cider
        type: deploy
    spec:
      containers:
        - name: main
          image: docker.io/smuda/demo-rollouts:latest
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: "{{ .Values.version }}"
            - name: GOOD
              {{ if .Values.isGood }}
              value: "yes"
              {{- else }}
              value: "no"
              {{- end }}
            - name: ROLE
              valueFrom:
                fieldRef:
                  fieldPath: "metadata.labels['role']"
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 30000
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1G
{{- end -}}
