apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cider
spec:
  endpoints:
  - honorLabels: false
    interval: 5s
    path: /metrics
    port: http
  namespaceSelector:
    matchNames:
    - app-cider
  selector:
    matchLabels:
      app: cider
