apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate
spec:
  args:
    - name: ingress
  metrics:
    - name: success-rate
      interval: 10s
      successCondition: result[0] >= 90
      failureCondition: result[0] < 90
      #failureCondition: result < 90
      #failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.addon-prometheus.svc:9090
          query: >+
            100 *
            sum (irate(nginx_ingress_controller_requests{ingress="cider",status="200"} [60s]))
            /
            sum(irate(nginx_ingress_controller_requests{ingress="cider"}[60s]))
