apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
    name: good-traffic
spec:
  metrics:
    - name: failures
      count: 10
      interval: 10s
      successCondition: "all(result, # < 5)"
      failureLimit: 2
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
          query: |
            60 * rate(cider_bad_processed_apples_total{namespace="{{.Release.Namespace }}",role="canary"} [1m])
