{{- if .Values.rollout.use -}}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: cider
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    canary:
      maxUnavailable: 0
      maxSurge: 2

      # Metadata which will be attached to the canary pods. This metadata will
      # only exist during an update, since there are no canary pods in a fully
      # promoted rollout.
      canaryMetadata:
        labels:
          environment: canary
      # metadata which will be attached to the stable pods
      stableMetadata:
        labels:
          role: stable

      {{- if .Values.rollout.metrics.use }}
      analysis:
        #args:
        #  - name: cider
        #    value: rollouts-demo-canary
        templates:
          - templateName: good-traffic
      {{- end }}
      steps:
        - setWeight: 20
        {{- if .Values.rollout.metrics.use }}
        # an inline analysis step
        - analysis:
            templates:
              - templateName: good-traffic
        {{- end }}
        - setWeight: 40
        - pause: {}
        - setWeight: 60
        - pause: {duration: 10}
        - setWeight: 80
        - pause: {duration: 10}

  selector:
    matchLabels:
      app: cider
      type: rollout
  template:
    metadata:
      labels:
        app: cider
        type: rollout
    spec:
      containers:
        - name: main
          image: docker.io/smuda/demo-rollouts:latest
          imagePullPolicy: Always
          env:
            - name: VERSION
              value: "{{ .Values.version }}"
            - name: GOOD
              {{ if .Values.isGood }}
              value: "yes"
              {{- else }}
              value: "no"
              {{- end }}
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              port: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 30000
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /tmp
              name: tmp
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      volumes:
        - name: tmp
          emptyDir:
            sizeLimit: 1G
{{- end -}}
