apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: app-cider
  namespace: argocd
spec:
  destination:
    namespace: app-cider
    server: https://kubernetes.default.svc
  project: apps
  source:
    helm:
      releaseName: cider
      valueFiles:
      - values-deploy.yaml
      version: v3
    path: app/helm/
    repoURL: https://github.com/smuda/demo-argo-rollouts.git
    targetRevision: feature/build
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/audit: restricted
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/warn: restricted
    syncOptions:
    - CreateNamespace=true
