rollout:
  use: true

  trafficRouting:
    nginx:
      # Reference to an Ingress which has a rule pointing to the stable service (e.g. rollouts-demo-stable)
      # This ingress will be cloned with a new name, in order to achieve NGINX traffic splitting.
      stableIngress: cider
      canaryIngress: cider-canary

  metrics:
    use: false
