apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
    name: good-traffic
spec:
  metrics:
    - name: failures
      count: 10
      interval: 10s
      successCondition: "all(result, # < 10.0)"
      failureLimit: 3
      provider:
        prometheus:
          address: http://prometheus-kube-prometheus-prometheus.addon-prometheus.svc.cluster.local:9090
          query: |
            cider_bad_processed_apples_total{namespace="{{.Release.Namespace }}"}
